# Generated by Django 4.1.2 on 2022-11-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ImageField(blank=True, upload_to="images/category/"),
        ),
    ]
