# Generated by Django 4.1.2 on 2022-12-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribtion',
            new_name='Subscription',
        ),
    ]
