# Generated by Django 4.1.2 on 2022-12-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_change_user_model_fields"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subscribtion",
            new_name="Subscription",
        ),
    ]
