# Generated by Django 4.1.2 on 2022-12-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='state',
            field=models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], default='opened', max_length=25),
        ),
    ]
