# Generated by Django 4.1.2 on 2023-01-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_create_meals_rate_model_alter_meal_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="chef",
            name="bio",
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="chef",
            name="description",
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="chef",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
