# Generated by Django 4.1.2 on 2023-01-17 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_create_wish_list_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='chef',
            field=models.ForeignKey(db_column='chef', on_delete=django.db.models.deletion.CASCADE, to='core.chef'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
