# Generated by Django 4.1.2 on 2023-01-17 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_change_subscription_column_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='chef',
            field=models.ForeignKey(db_column='chef', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_set', to='core.chef'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
