# Generated by Django 4.1.2 on 2023-01-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_subscription_chef_alter_subscription_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='delivery_cost',
            field=models.IntegerField(default=0),
        ),
    ]
