# Generated by Django 4.1.2 on 2023-01-27 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_subscription_chef_alter_subscription_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='delivery_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='additives',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='allergens',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='delivery_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
