# Generated by Django 4.1.2 on 2023-01-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_Add_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
