# Generated by Django 4.1.2 on 2023-01-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_chef_delivery_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='additives',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='allergens',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='delivery_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
