# Generated by Django 4.1.2 on 2023-01-27 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_New_cart_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('loc_lan', models.DecimalField(decimal_places=6, max_digits=9)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
