# Generated by Django 4.1.2 on 2023-01-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_Add_Order_SubOrder_Model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
