# Generated by Django 4.1.2 on 2023-01-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="city",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="country",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="department_number",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[("Work", "Work"), ("Home", "Home")],
                default="Home",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="street",
            field=models.TextField(null=True),
        ),
    ]
