# Generated by Django 4.1.2 on 2023-01-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_location_city_location_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suborder",
            name="cart_items",
            field=models.ManyToManyField(
                related_name="order_item_set", to="core.cartitem"
            ),
        ),
    ]
