# Generated by Django 4.1.2 on 2023-01-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_order_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.TextField(null=True),
        ),
    ]
